version: "2"

# networks:
#   app-tier:
#     driver: bridge

services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env
    depends_on:
       - db
    volumes:
      - ./webapp:/opt/webapp
    command: npm start
  db:
    image: bitnami/postgresql:latest
    restart: always
    env_file: .env
    # networks:
    #   - app-tier
    ports:
    - "2222:5432"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    # networks:
    #   - app-tier
